name: qr_studio_example
description: Example app for the qr_studio package.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_studio:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
