/**
 * Server-side rendering. Reuses the EXACT same core as the browser app
 * (buildMatrix + renderSVG + subCellFill) so a code generated by the service is
 * byte-for-byte the same decision as one generated in the studio UI — then
 * rasterises to PNG with resvg-wasm and proves scannability with jsQR on the
 * rendered pixels (no separate decode step needed).
 */
import { Resvg, initWasm } from '@resvg/resvg-wasm';
// wrangler bundles the wasm as a WebAssembly.Module import.
import resvgWasm from '@resvg/resvg-wasm/index_bg.wasm';
import jsQR from 'jsqr';

import { buildMatrix } from '../../src/qr/matrix';
import { renderSVG } from '../../src/qr/svg';
import type { QrRequest } from './validate';

// initWasm must run once per isolate; guard with a shared promise so concurrent
// requests don't race the initialisation.
let wasmReady: Promise<void> | null = null;
function ensureWasm(): Promise<void> {
  if (!wasmReady) wasmReady = initWasm(resvgWasm as unknown as WebAssembly.Module);
  return wasmReady;
}

export function buildSvg(req: QrRequest): string {
  const matrix = buildMatrix(req.data, req.ec);
  return renderSVG({
    matrix,
    quietModules: req.quiet,
    fg: req.fg,
    bg: req.bg,
    sampler: null, // image/halftone styles need a pixel source; not offered server-side
    protectPatterns: true,
    colorStyle: req.style,
    brandColor: req.brand,
    sub: req.sub,
    pixelSize: req.size,
    centerImage: req.logo
      ? { href: req.logo, ratio: req.logoRatio, plate: req.logoPlate }
      : null,
  });
}

export interface RasterResult {
  png: Uint8Array;
  width: number;
  height: number;
  pixels: Uint8Array; // RGBA
}

export async function rasterize(svg: string, size: number, bg: string): Promise<RasterResult> {
  await ensureWasm();
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: size },
    background: bg,
  });
  const rendered = resvg.render();
  const png = rendered.asPng();
  const { width, height, pixels } = rendered;
  return { png, width, height, pixels };
}

/**
 * Decode the rendered pixels and confirm they carry exactly the payload we
 * encoded. Returns true only on an exact round-trip — the same guarantee the
 * in-browser "verified scannable" badge gives, enforced on the server.
 */
export function verifyPixels(r: RasterResult, expected: string): boolean {
  const code = jsQR(new Uint8ClampedArray(r.pixels.buffer, r.pixels.byteOffset, r.pixels.byteLength), r.width, r.height);
  return !!code && code.data === expected;
}
